### ISSUE TITLE
Maybe a minor error in the code snippet for "Setting up the Optimizer"?

### ISSUE THREAD

**Issue by JOE1994** [NVlabs/condensa#1]
Hello, 
In the ["Setting up the Optimizer" part from the LeNet5 tutorial](https://github.com/NVlabs/condensa/blob/gh-pages/notebooks/LeNet5.md#setting-up-the-optimizer), there is a text description as follows.

>  In our case, we run the L-C algorithm for 40 iterations using the hyper-parameter values shown above. LC hyper-parameter values for a number of common convolutional neural networks are also included in the /workspace/condensa/examples folder in the container.

However, the `steps` argument for the function `condensa.opt.LC` is set to 2 in the given code snippet. Shouldn't the 'steps' argument be set to 40 instead?

**Comment by srvm** [comment]
Thanks for pointing this out. Since the notebook is designed to be interactive, we didn't want it to take too long to execute, and hence set `steps` to 2. For a real-world run with a larger number of iterations, I'd recommend checking out the `examples/mnist/` folder and the `compress_lenet5.sh` script in it.
